Repository josefarias/hotwire_combobox, pull requests merged in 2024-03, with the labels that each got.

#51 Only consider unselected portion when autocompleting
  app/assets/javascripts/controllers/hw_combobox_controller.js
  app/assets/javascripts/hw_combobox/helpers.js
  app/assets/javascripts/hw_combobox/models/combobox/autocomplete.js
  app/assets/javascripts/hw_combobox/models/combobox/dialog.js
  app/assets/javascripts/hw_combobox/models/combobox/filtering.js
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  test/system/hotwire_combobox_test.rb
Labels: bug

#52 Consider current selection in immediately autocompletable value
  app/assets/javascripts/hw_combobox/models/combobox/autocomplete.js
  app/assets/javascripts/hw_combobox/models/combobox/toggle.js
  test/system/hotwire_combobox_test.rb
Labels: bug

#53 Ensure -> Lock-In
  app/assets/javascripts/controllers/hw_combobox_controller.js
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  app/assets/javascripts/hw_combobox/models/combobox/toggle.js
  test/system/hotwire_combobox_test.rb
Labels: cosmetic

#54 Update gem description
  hotwire_combobox.gemspec
Labels: cosmetic

#55 Only use <li> elements as listbox children
  app/presenters/hotwire_combobox/component.rb
  app/views/hotwire_combobox/_next_page.turbo_stream.erb
  app/views/hotwire_combobox/_paginated_options.turbo_stream.erb
  app/views/hotwire_combobox/_pagination.html.erb
  app/views/hotwire_combobox/combobox/_paginated_listbox.html.erb
  lib/hotwire_combobox/helper.rb
  test/helpers/hotwire_combobox/helper_test.rb
Labels: bug

#58 @states -> @state_options
  test/dummy/app/controllers/comboboxes_controller.rb
  test/dummy/app/views/comboboxes/formbuilder.html.erb
  test/dummy/app/views/comboboxes/html_options.html.erb
  test/dummy/app/views/comboboxes/inline_autocomplete.html.erb
  test/dummy/app/views/comboboxes/list_autocomplete.html.erb
  test/dummy/app/views/comboboxes/open.html.erb
  test/dummy/app/views/comboboxes/plain.html.erb
  test/dummy/app/views/comboboxes/prefilled.html.erb
  test/dummy/app/views/comboboxes/required.html.erb
Labels: cosmetic

#66 Generate an id if one is not passed to combobox
  app/presenters/hotwire_combobox/component.rb
Labels: bug

#67 Add rubocop
  .github/workflows/ci.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  bin/rubocop
  lib/hotwire_combobox/engine.rb
  test/dummy/app/controllers/new_options_forms_controller.rb
  test/dummy/app/controllers/users_controller.rb
  test/test_helper.rb
Labels: cosmetic

#72 Add GH actions to dependabot
  .github/dependabot.yml
Labels: dependencies

#74 Momoize potentially random ids
  app/presenters/hotwire_combobox/component.rb
  app/presenters/hotwire_combobox/listbox/option.rb
Labels: bug

#98 Fix filtering when locking in selection
  app/assets/javascripts/hw_combobox/models/combobox/filtering.js
  test/dummy/app/controllers/comboboxes_controller.rb
  test/dummy/app/views/comboboxes/conflicting_order.html.erb
  test/dummy/config/routes.rb
  test/system/hotwire_combobox_test.rb
Labels: bug

#111 Detangle autocompletion, selection, and filtering
  app/assets/javascripts/controllers/hw_combobox_controller.js
  app/assets/javascripts/hw_combobox/models/combobox/async_loading.js
  app/assets/javascripts/hw_combobox/models/combobox/autocomplete.js
  app/assets/javascripts/hw_combobox/models/combobox/events.js
  app/assets/javascripts/hw_combobox/models/combobox/filtering.js
  app/assets/javascripts/hw_combobox/models/combobox/options.js
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  app/assets/javascripts/hw_combobox/models/combobox/toggle.js
  app/assets/javascripts/hw_combobox/models/combobox/validity.js
  app/presenters/hotwire_combobox/component.rb
  test/dummy/app/javascript/controllers/combobox/events_controller.js
  test/dummy/app/views/comboboxes/custom_events.html.erb
  test/system/hotwire_combobox_test.rb
Labels: breaking

#112 Refactor names in codebase
  app/assets/javascripts/controllers/hw_combobox_controller.js
  app/assets/javascripts/hw_combobox/models/combobox.js
  app/assets/javascripts/hw_combobox/models/combobox/dialog.js
  app/assets/javascripts/hw_combobox/models/combobox/events.js
  app/assets/javascripts/hw_combobox/models/combobox/filtering.js
  app/assets/javascripts/hw_combobox/models/combobox/form_field.js
  app/assets/javascripts/hw_combobox/models/combobox/options.js
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  app/assets/javascripts/hw_combobox/models/combobox/toggle.js
  app/assets/javascripts/hw_combobox/models/combobox/validity.js
  app/presenters/hotwire_combobox/listbox/option.rb
Labels: cosmetic

#108 Show clear widget on prefilled state
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  test/system/hotwire_combobox_test.rb
Labels: bug

#120 Rename events
  app/assets/javascripts/hw_combobox/models/combobox/events.js
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  app/assets/javascripts/hw_combobox/models/combobox/toggle.js
  test/dummy/app/javascript/controllers/combobox/events_controller.js
  test/dummy/app/views/comboboxes/custom_events.html.erb
  test/dummy/app/views/comboboxes/multiselect_custom_events.html.erb
  test/system/hotwire_combobox_test.rb
Labels: breaking

#129 Remove input outline when focused
  app/assets/stylesheets/hotwire_combobox.css
Labels: bug

#131 Extend outline fix to focus-visible and within
  app/assets/stylesheets/hotwire_combobox.css
Labels: bug

#132 Reconnect after element morph
  app/assets/javascripts/controllers/hw_combobox_controller.js
  app/presenters/hotwire_combobox/component.rb
  test/dummy/app/controllers/comboboxes_controller.rb
  test/dummy/app/controllers/users_controller.rb
  test/dummy/app/views/comboboxes/morph.html.erb
  test/dummy/app/views/layouts/application.html.erb
  test/dummy/config/routes.rb
  test/system/hotwire_combobox_test.rb
Labels: bug
