Repository josefarias/hotwire_combobox, pull requests merged in 2025-03, with the labels that each got.

#241 Bump dependencies
  Gemfile.lock
Labels: dependencies, internal

#246 Stop installing chromedriver in ci
  .github/workflows/ci.yml
Labels: internal

#235 Decouple opening from focusing
  CONTRIBUTING.md
  README.md
  app/assets/javascripts/controllers/hw_combobox_controller.js
  app/assets/javascripts/hotwire_combobox.esm.js
  app/assets/javascripts/hw_combobox/models/combobox/autocomplete.js
  app/assets/javascripts/hw_combobox/models/combobox/filtering.js
  app/assets/javascripts/hw_combobox/models/combobox/multiselect.js
  app/assets/javascripts/hw_combobox/models/combobox/navigation.js
  app/assets/javascripts/hw_combobox/models/combobox/selection.js
  app/assets/javascripts/hw_combobox/models/combobox/toggle.js
  app/presenters/hotwire_combobox/component/markup/dialog.rb
  app/presenters/hotwire_combobox/component/markup/input.rb
  app/presenters/hotwire_combobox/component/markup/wrapper.rb
  test/dummy/app/views/comboboxes/custom_events.html.erb
  test/dummy/app/views/comboboxes/multiselect_custom_events.html.erb
  test/lib/helpers/combobox_assertions_helper.rb
  test/system/custom_events_test.rb
  test/system/keyboard_navigation_test.rb
  test/system/multiselect_test.rb
  test/system/selection_test.rb
Labels: breaking

#240 Allow additional actions on input
  app/presenters/hotwire_combobox/component/markup/input.rb
  test/presenters/hotwire_combobox/component_test.rb
Labels: bug
